### ISSUE TITLE
Investigate if `dApp Development` section of the docs was affected by devpack-independence#1050 PR

### ISSUE THREAD

**Issue by thedanielmark** [neow3j/neow3j-docs#32]
https://github.com/neow3j/neow3j/pull/1050 included some dependency changes and we should check if the following statement in the [dApp Development](https://github.com/neow3j/neow3j-docs/blob/032dd7342ae262868355a4a39e0d6a34abe462ad/docs/neo-n3/dapp_development/introduction.md) section of the docs still holds true:

https://github.com/neow3j/neow3j-docs/blob/dff3e9b015c473a797b5b3780b2b9c75b3715c66/docs/neo-n3/dapp_development/introduction.md?plain=1#L15-L17

---

> I'm not so sure if this part of the docs was affected by https://github.com/neow3j/neow3j/pull/1050.
>
> @thedanielmark, my suggestion is: create an issue here in `neow3j-docs` to investigate that (assigned it to you), and add to our AxLabs board to tackle in the upcoming sprint.

_Originally posted by @gsmachado in https://github.com/neow3j/neow3j-docs/pull/30#discussion_r1590283844_

**Comment by mialbu** [comment]
I've just checked this and the statement remains true. The `contract` module has an `api` configuration for the `core` module. It transitively exposes the `core` module to any project that has the `contract` module as a dependency. In bold words: If you have the `contract` module as a dependency in your project, you'll automatically have `core` as a dependency as well and can use its methods etc. accordingly.
