### ISSUE TITLE
improve docs for the Storage

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j-docs#6]
Provide more examples about the `Storage`. Check the TODOs in the file `docs/neo3_guides/compiler_devpack/devpack.md`.

**Comment by csmuller** [comment]
We are trying to handle issues exclusively in our main [repo](https://github.com/neow3j/neow3j) and this one is covered by another issue there ([#487](https://github.com/neow3j/neow3j/issues/487))
